name: agconnect_crash_example
description: Demonstrates how to use the agconnect_crash plugin.
version: 1.9.1+301

publish_to: "none" 

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  huawei_analytics: ^6.5.0+301
  innim_agconnect_crash:
    # When depending on this package from a real application you should use:
    #   agconnect_crash: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../


  cupertino_icons: ^1.0.5

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter




flutter:
 
  uses-material-design: true

  